name: Deploy Blazor to Pages
on:
  push:
    branches: [ main ]
permissions:
  contents: read
  pages: write
  id-token: write
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with: { dotnet-version: '8.0.x' }
      - name: Publish
        run: dotnet publish -c Release -o publish
      - name: Fix base href for GitHub Pages
        run: |
          repo="${{ github.event.repository.name }}"
          index="publish/wwwroot/index.html"
          sed -i "s|<base href=\"/\" />|<base href=\"/${repo}/\" />|" "$index"
      - uses: actions/configure-pages@v5
      - uses: actions/upload-pages-artifact@v3
        with: { path: publish/wwwroot }
      - uses: actions/deploy-pages@v4
